platform :ios, '8.0'

target 'chunky' do
  use_frameworks!

  # Required by RNFirebase
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/AppIndexing'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'
  
  target 'chunkyTests' do
    inherit! :search_paths
  end

end
